### ISSUE TITLE
Multiple dynamics functions F within a batch

### ISSUE THREAD

**Issue by qu-gg** [martenlienen/torchode#1]
First off, thanks much for sharing this awesome library! Excited to try it out.

I had a question relating to using the parallelization of this library in order to solve over multiple ODE dynamics functions f within the same batch. For example, if I had a unique function f<sub>i</sub> per sample, is there a recommended way to pass in its corresponding parameters (or its index) to reference in the ODE step function?

Thanks!

**Comment by martenlienen** [comment]
Hey, thanks for trying out my library!

If you want to pass extra arguments to your model that do not vary over time, you can pass an arbitrary object such as a tensor or a tuple of tensors via the `args` argument. These will be passed on to your model as an extra `args` argument every time it is called, i.e.
```python
class Model(nn.Module):
    def forward(self, t, y, args):
        pass
```
In general, I am unsure if evaluating multiple completely different models in this way is the way to go, because if the models are actually different architectures you won't be able to avoid splitting the batches into the individual samples and then handing each sample to its corresponding model, though you can figure out the association by passing in some index via the `args`. If you want to learn different parameters for the *same* architecture, e.g. a different MLP for each sample in a batch, it should be possible, but you would have to build your own "parallel" layers. So instead of `nn.Linear` you could use a `Conv2D` with the kernel size configured appropriately.
