### ISSUE TITLE
parallel parameters for ode instances?

### ISSUE THREAD

**Issue by nihcompmed** [martenlienen/torchode#18]
In running the example on your Github exactly as written (copied and pasted into Spyder), I get the following error:

Traceback (most recent call last):

  File ~/opt/anaconda3/envs/torch/lib/python3.8/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/.spyder-py3/temp.py:22
    jit_solver = torch.jit.script(solver)

  File ~/opt/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_script.py:1286 in script
    return torch.jit._recursive.create_script_module(

  File ~/opt/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_recursive.py:476 in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)

  File ~/opt/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_recursive.py:542 in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)

  File ~/opt/anaconda3/envs/torch/lib/python3.8/site-packages/torch/jit/_recursive.py:393 in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)

RuntimeError: type INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/jit/ir/ir.h":1488, please report a bug to PyTorch. 

The other question I had is not an issue: Is it possible to have a tensor of parameters for the system of differential equations? I.e. the functional form of the ODE is the same for each sample but the parameters are different. I see in your example that the initial conditions can be different and the evaluation time points can be different, but given where the term is defined, is it possible for f(t,x) to be replaced with F(alpha) which returns f(t,x; alpha), and then one would pass in tensors for alpha, initial conditions and time points? I could, of course, put dummy equations with vanishing derivatives for any parameters and then pass them in as initial values that will just stay constant, but that does not seem very graceful.

Thank you.

**Comment by martenlienen** [comment]
Hey, thanks for trying torchode! Unfortunately, the code in the readme works for me and I cannot reproduce the problem, so I cannot help you with that. pytorch's JIT compiler is pretty finicky in my experience and if you want to use it more heavily, you will not get around dealing with and debugging these kind of errors, because they can be very specific to your setup. First thing I would try would be a more recent python version but it could be something else completely.

Regarding your second question, I have added a [page on passing extra arguments](https://torchode.readthedocs.io/en/latest/extra-args/) to the documentation. I hope that answers your question. Otherwise, please feel free to follow up.
