### ISSUE TITLE
torchode for score-based models

### ISSUE THREAD

**Issue by gisilvs** [martenlienen/torchode#24]
Hi there, I have been trying to use this library for computing the likelihood of score based models as done in [https://github.com/yang-song/score_sde_pytorch/blob/main/likelihood.py](url), but without success. Woudl it be possible to provide a working example?

**Comment by martenlienen** [comment]
I am sorry, but I don't have the capacity at the moment to implement a full score-based model as an example. I see that it might not work because torchode is only made for ODEs and I believe this requires an SDE solver, though you might be able to extend torchode to also solve SDEs. However, I cannot help you with that. Where exactly are you having problems? What is the error message you get?

**Comment by martenlienen** [comment]
Hey, no it does not update the model. It just lets you compute gradients with the adjoint method. But if you don't care about gradients and training, you can also just use the normal `to.AutoDiffAdjoint`.
