### ISSUE TITLE
Adding an event function in solver

### ISSUE THREAD

**Issue by Basicallyimwell** [martenlienen/torchode#26]
Hello Marten thanks for your work! 

For my task, I would like to integrate some latent variables into a steady state, which means I need an evaluation function to check my y_solution. The termination criteria is simply a boolean, that just **norm(vector field at t) < atol + rtol * norm(yt-1)** .

As a newcomer user from torchdiffeq, would you like to provide me some suggestions, like where should I add my event_fn/ modify the code in order to get the job done? (I am from the clinical medicine field haha, therefore your suggestions would be very valuable and helpful to me!)

**Comment by martenlienen** [comment]
Hey Rondy,

Thanks for your support! Unfortunately, torchode does not implement event functions. I decided against that, when I made it, because a correct implementation would make the solver loop quite a bit more complicated and I wanted to keep the complexity as low as possible.

If you want to implement it yourself, you would most likely add the termination logic [here](https://github.com/martenlienen/torchode/blob/main/torchode/adjoints.py#L187) (detect a sign change of the event function), though you would also need some extra logic to keep track of the step and then binary search or so at the end, to really nail down the zero point of the event function.
